# Generated by Django 3.2.7 on 2021-11-08 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContestantPost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='votes',
            new_name='contestent',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'contest', 'contestent')},
        ),
    ]
