# Generated by Django 3.2.7 on 2021-11-09 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContestantPost', '0002_auto_20211108_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='contestent',
            new_name='contestant',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'contest', 'contestant')},
        ),
    ]
